WBHP -- Well BHP
/
WWMR  -- Water Mass Rate
/
WWPRT -- Water Production Rate Target
/
WWPR  -- Water Production Rate 
/
WVPR  -- Water Reservoir Volume Production Rate
/
WVPRT  -- Water Reservoir Volume Production Rate Target
/
WVPGR -- Res Volume Production Guide Rate
/
WGPR -- Gas Production Rate
/
WOPR -- Oil Production Rate
/
WTEMP --  Production Temp
/
WSTPR --  Steam Production Temp
/
WSQU -- Injected Steam Quality
/
WWIR -- Water Injetcion Rate
/
